# Generated by Django 5.0.7 on 2024-07-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmdetails',
            old_name='Alerttime',
            new_name='alert_before',
        ),
        migrations.RenameField(
            model_name='alarmdetails',
            old_name='Datetime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='alarmdetails',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='alarmdetails',
            old_name='Title',
            new_name='title',
        ),
    ]
